### ISSUE TITLE
Can not install pip

### ISSUE THREAD

**Issue by Huxpro** [JamesPan/duoshuo-migrator#1]
Hey, I try to install pip, follow the [official site](https://pip.pypa.io/en/stable/installing/#install-pip) .
But...after I download `get-pip.py` and try to run `python get-pip.py`...things gonna wrong..

```
Collecting pip
  Using cached pip-7.1.2-py2.py3-none-any.whl
  Hash of the package https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl#md5=5ff9fec0be479e4e36df467556deed4d (from https://pypi.python.org/simple/pip/) (41d52eb3edd3e85cddf51284a6a0510b) doesn't match the expected hash 5ff9fec0be479e4e36df467556deed4d!
Bad md5 hash for package https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl#md5=5ff9fec0be479e4e36df467556deed4d (from https://pypi.python.org/simple/pip/)
```

I dont know what happened exactly...may be I download the wrong file..? 
So..I can not run your script until this solved. Sigh

**Comment by JamesPan** [comment]
@Huxpro try to break the gfw than install pip

**Comment by Huxpro** [comment]
@JamesPan  

Broken, try again but failed.. Let me re-download it and try

**Comment by Huxpro** [comment]
@JamesPan 

Well..it's not gfw's stuff, `sudo` is help, installed now
